# Generated by Django 6.0 on 2025-12-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allow_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='composition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='fillings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='manufacturing_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='max_quantity_per_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='start_sales_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='storage_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.dish')),
            ],
        ),
    ]
