# Generated by Django 6.0 on 2025-12-14 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dish_allow_preorder_dish_composition_dish_dimensions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Time in minutes to cook this dish'),
        ),
        migrations.AddField(
            model_name='order',
            name='acceptance_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_cooking_time',
            field=models.PositiveIntegerField(default=0, help_text='Total minutes'),
        ),
        migrations.AddField(
            model_name='order',
            name='finished_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('WAITING_FOR_ACCEPTANCE', 'Waiting for Acceptance'), ('COOKING', 'Cooking'), ('READY_FOR_REVIEW', 'Ready for Review (Photo Uploaded)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute Open')], default='WAITING_FOR_PAYMENT', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producer',
            name='closing_time',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='producer',
            name='consecutive_rejections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producer',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='producer',
            name='penalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='disputes_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='unjustified_cancellations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('QUALITY', 'Quality Issue'), ('NOT_RECEIVED', 'Not Received'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED_BUYER_WON', 'Resolved (Buyer Won)'), ('RESOLVED_SELLER_WON', 'Resolved (Seller Won)'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('compensation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.order')),
            ],
        ),
    ]
