# Generated by Django 6.0 on 2025-12-14 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dish_cooking_time_minutes_order_acceptance_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producer',
            name='extra_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra % to boost ranking', max_digits=5),
        ),
        migrations.AddField(
            model_name='producer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_type',
            field=models.CharField(choices=[('SELF_EMPLOYED', 'Self Employed (5%)'), ('INDIVIDUAL_ENTREPRENEUR', 'Individual Entrepreneur (10%)')], default='SELF_EMPLOYED', max_length=50),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed (Kontur)'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='api.producer')),
            ],
        ),
    ]
