# Generated by Django 6.0 on 2025-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dish_favorites_count_dish_in_cart_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='favorites_count',
        ),
        migrations.AddField(
            model_name='order',
            name='gift_proof_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_specified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_approved_by_buyer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_new_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_requested_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
