# Generated by Django 6.0 on 2025-12-14 11:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_dish_favorites_count_order_gift_proof_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('BUILDING', 'To Building'), ('DOOR', 'To Door')], default='BUILDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producer',
            name='delivery_price_to_building',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producer',
            name='delivery_price_to_door',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producer',
            name='delivery_pricing_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producer',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producer',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('WAITING_FOR_RECIPIENT', 'Waiting for Recipient (Gift)'), ('WAITING_FOR_ACCEPTANCE', 'Waiting for Acceptance'), ('COOKING', 'Cooking'), ('READY_FOR_REVIEW', 'Ready for Review (Photo Uploaded)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute Open')], default='WAITING_FOR_PAYMENT', max_length=50),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount Amount'), ('FREE_DELIVERY', 'Free Delivery'), ('GIFT', 'Edible Gift')], max_length=20)),
                ('reward_value', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='api.producer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='applied_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocode'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_taste', models.PositiveIntegerField(default=5)),
                ('rating_appearance', models.PositiveIntegerField(default=5)),
                ('rating_service', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('refund_offered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.producer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.review'),
        ),
    ]
