# Generated by Django 6.0 on 2025-12-15 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_helparticle_producer_user_notification_paymentmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('PASSWORD', 'Password')], max_length=20)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
