# Generated by Django 6.0 on 2025-12-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pendingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(blank=True, default='LOCAL', max_length=20),
        ),
    ]
