# Generated by Django 6.0 on 2025-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_profile_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='role',
            field=models.CharField(default='CLIENT', max_length=20),
        ),
    ]
