# Generated by Django 6.0 on 2025-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pendingregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
