# Generated by Django 6.0 on 2025-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pendingregistration_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
