# Generated by Django 6.0 on 2025-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_producer_pickup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='employees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='producer',
            name='requisites',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
