# Generated by Django 6.0 on 2025-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_producer_employees_producer_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
