# Generated by Django 6.0 on 2025-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_producer_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Calories per 100g'),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Carbohydrates per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='dish',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Fats per 100g', max_digits=5),
        ),
        migrations.AddField(
            model_name='dish',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Proteins per 100g', max_digits=5),
        ),
    ]
