# Generated by Django 6.0 on 2025-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_dish_calories_dish_carbs_dish_fats_dish_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dish',
            name='allow_preorder',
            field=models.BooleanField(default=True),
        ),
    ]
