# Generated by Django 6.0 on 2025-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_dish_min_quantity_alter_dish_allow_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
    ]
