# Generated by Django 6.0 on 2025-12-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_dish_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]

