# Generated by Django 5.1.4 on 2025-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_order_delivery_address_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tinkoff_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatcomplaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('WAITING_FOR_RECIPIENT', 'Waiting for Recipient (Gift)'), ('WAITING_FOR_ACCEPTANCE', 'Waiting for Acceptance'), ('COOKING', 'Cooking'), ('READY_FOR_REVIEW', 'Ready for Review (Photo Uploaded)'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('DELIVERING', 'Delivering'), ('ARRIVED', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTE', 'Dispute Open')], default='WAITING_FOR_PAYMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingchange',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
