# Generated by Django 5.1.4 on 2025-12-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_toppings',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, price} selected toppings'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_toppings',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, price} selected toppings'),
        ),
        migrations.CreateModel(
            name='DishTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='api.dish')),
            ],
        ),
    ]
