# Generated by Django 5.1.4 on 2026-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_order_cancelled_at_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_accrued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('NOT_ACCRUED', 'Not Accrued'), ('ACCRUED', 'Accrued'), ('PAID_OUT', 'Paid Out')], default='NOT_ACCRUED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='producer_gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='producer_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_tips_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
