# Generated by Django 5.1.4 on 2026-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_gift_create_idempotency_published_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='api_outboxe_status_53e782_idx',
            old_name='outbox_status_next_attempt',
        ),
        migrations.RenameIndex(
            model_name='outboxevent',
            new_name='api_outboxe_status_6c53bf_idx',
            old_name='outbox_status_created',
        ),
        migrations.AddField(
            model_name='profile',
            name='gift_notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITING_SELLER', 'Waiting Seller'), ('WAITING_SUPPORT', 'Waiting Support'), ('RESOLVED_BUYER_WON', 'Resolved (Buyer Won)'), ('RESOLVED_SELLER_WON', 'Resolved (Seller Won)'), ('RESOLVED_PARTIAL', 'Resolved (Partial Refund)'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='giftactivationattempt',
            name='outcome',
            field=models.CharField(choices=[('ATTEMPTED', 'Attempted'), ('SUCCESS', 'Success')], default='ATTEMPTED', max_length=16),
        ),
        migrations.AlterField(
            model_name='giftpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='giftproduct',
            name='type',
            field=models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('FIXED_MEAL', 'Fixed Meal'), ('BUNDLE', 'Bundle')], max_length=32),
        ),
        migrations.AlterField(
            model_name='refundoperation',
            name='source',
            field=models.CharField(choices=[('SLA', 'Sla'), ('DISPUTE', 'Dispute'), ('CHARGEBACK', 'Chargeback'), ('MANUAL', 'Manual')], max_length=16),
        ),
        migrations.AlterField(
            model_name='refundoperation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PSP_PENDING', 'Psp Pending'), ('PSP_COMPLETED', 'Psp Completed'), ('PSP_FAILED', 'Psp Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=32),
        ),
    ]
