# Generated by Django 5.1.4 on 2026-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_outbox_status_next_attempt_api_outboxe_status_53e782_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
