# Generated by Django 5.1.4 on 2026-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_order_recipient_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
