# Generated by Django 5.1.4 on 2026-01-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_order_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
