# Generated by Django 5.1.4 on 2026-01-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_order_is_anonymous'),
    ]

    operations = [
    ]
