# Generated by Django 5.1.4 on 2026-01-22 04:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_auto_20260120_0113"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteDish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("BUILDING", "To Building"), ("DOOR", "To Door")],
                        default="BUILDING",
                        max_length=20,
                    ),
                ),
                ("delivery_address_text", models.TextField(blank=True, default="")),
                ("apartment", models.CharField(blank=True, default="", max_length=50)),
                ("entrance", models.CharField(blank=True, default="", max_length=50)),
                ("floor", models.CharField(blank=True, default="", max_length=50)),
                ("intercom", models.CharField(blank=True, default="", max_length=50)),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "selected_toppings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, price} selected toppings",
                    ),
                ),
                ("is_gift", models.BooleanField(default=False)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("recipient_phone", models.CharField(blank=True, max_length=50)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("recipient_address_text", models.TextField(blank=True)),
                (
                    "recipient_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "recipient_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "recipient_specified_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "query_params",
                    models.JSONField(help_text="JSON representation of search filters"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("results_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="rating_packaging",
            field=models.PositiveIntegerField(
                default=5, help_text="Оценка упаковки (1-5)"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_portion",
            field=models.PositiveIntegerField(
                default=5, help_text="Оценка размера порции (1-5)"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="seller_response",
            field=models.TextField(blank=True, help_text="Ответ продавца на отзыв"),
        ),
        migrations.AddField(
            model_name="review",
            name="seller_response_at",
            field=models.DateTimeField(
                blank=True, help_text="Время ответа продавца", null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="video",
            field=models.URLField(
                blank=True, help_text="URL к видео отзыва", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tinkoff_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="delivery_pricing_rules",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.validators.DeliveryPricingRulesValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="delivery_zones",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.validators.DeliveryZonesValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="documents",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.validators.DocumentsValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="employees",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.validators.EmployeesValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="requisites",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[core.validators.RequisitesValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="weekly_schedule",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[core.validators.WeeklyScheduleValidator()],
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="api_order_status_1d49fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="api_order_user_id_536555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["producer", "status"], name="api_order_produce_2856a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="api_order_created_7fb22c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="api_order_status_dee4b6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tinkoff_payment_id"], name="api_order_tinkoff_fe0fc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["recipient_token"], name="api_order_recipie_35eec8_idx"
            ),
        ),
        migrations.AddField(
            model_name="favoritedish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.dish"
            ),
        ),
        migrations.AddField(
            model_name="favoritedish",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_dishes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderdraft",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_drafts",
                to="api.dish",
            ),
        ),
        migrations.AddField(
            model_name="orderdraft",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritedish",
            unique_together={("user", "dish")},
        ),
        migrations.AddIndex(
            model_name="orderdraft",
            index=models.Index(
                fields=["user", "-updated_at"], name="api_orderdr_user_id_2f0252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdraft",
            index=models.Index(
                fields=["user", "dish"], name="api_orderdr_user_id_2f92a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(
                fields=["user", "-created_at"], name="api_savedse_user_id_0da4b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="api_searchh_user_id_714456_idx"
            ),
        ),
    ]
