# Generated by Django 5.1.4 on 2026-01-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_favoritedish_orderdraft_savedsearch_searchhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritedish",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_dishes",
                to="api.dish",
            ),
        ),
    ]
