# Generated by Django 5.1.4 on 2026-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_alter_favoritedish_dish"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="repeat_purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dishimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dishimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_penalty_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_actual_arrival_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_expected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_late_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_penalty_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="penalty_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="penalty_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="recipient_sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="tips_tax_exempt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="kontur_sign_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="kontur_sign_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="payout",
            name="next_payout_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="payout_frequency",
            field=models.CharField(default="WEEKLY", max_length=20),
        ),
        migrations.AddField(
            model_name="payout",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="tax_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payout",
            name="tax_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="tax_payment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="producer",
            name="ban_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="producer",
            name="banned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producer",
            name="unban_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_by_producers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_problem_buyer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="problem_buyer_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="repeat_purchase_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="profile",
            name="repeated_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="promocode",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="promocode",
            name="sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promocode",
            name="sms_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="review",
            name="correction_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="correction_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="original_rating_appearance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="original_rating_service",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="original_rating_taste",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
