# Generated by Django 5.1.4 on 2026-01-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_dish_repeat_purchase_count_dishimage_is_primary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftactivationattempt",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="giftactivationidempotency",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="giftactivationidempotency",
            name="order",
        ),
        migrations.RemoveField(
            model_name="giftcreateidempotency",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="giftorder",
            name="gift_product",
        ),
        migrations.RemoveField(
            model_name="giftorder",
            name="order",
        ),
        migrations.RemoveField(
            model_name="giftorder",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="giftorder",
            name="recipient_user",
        ),
        migrations.RemoveField(
            model_name="giftpayment",
            name="gift",
        ),
        migrations.RemoveField(
            model_name="refundoperation",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="giftproduct",
            name="base_dish",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="api_order_recipie_35eec8_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="recipient_sms_sent",
        ),
        migrations.RemoveField(
            model_name="order",
            name="recipient_sms_sent_at",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="is_anonymous",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="is_gift",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_address_text",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_latitude",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_longitude",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_name",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_phone",
        ),
        migrations.RemoveField(
            model_name="orderdraft",
            name="recipient_specified_time",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gift_notification_preferences",
        ),
        migrations.AlterField(
            model_name="chatcomplaint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dishimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dishtopping",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="favoritedish",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="gift_proof_image",
            field=models.URLField(
                blank=True, help_text="Proof photo that gift was delivered", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Whether the sender should be hidden from recipient",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(
                default=False, help_text="Whether this is a gift order"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_address_text",
            field=models.TextField(
                blank=True, default="", help_text="Delivery address for gift recipient"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude of recipient address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude of recipient address",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of gift recipient",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number of gift recipient",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_specified_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When recipient specified delivery time",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Token for recipient to specify delivery details",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_token_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When recipient token expires", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_PAYMENT", "Waiting for Payment"),
                    ("WAITING_FOR_ACCEPTANCE", "Waiting for Acceptance"),
                    ("COOKING", "Cooking"),
                    ("READY_FOR_REVIEW", "Ready for Review (Photo Uploaded)"),
                    ("READY_FOR_DELIVERY", "Ready for Delivery"),
                    ("DELIVERING", "Delivering"),
                    ("ARRIVED", "Arrived at Destination"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DISPUTE", "Dispute Open"),
                ],
                default="WAITING_FOR_PAYMENT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pendingchange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pendingregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("DISCOUNT", "Discount Amount"),
                    ("FREE_DELIVERY", "Free Delivery"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="GiftActivationAttempt",
        ),
        migrations.DeleteModel(
            name="GiftActivationIdempotency",
        ),
        migrations.DeleteModel(
            name="GiftCreateIdempotency",
        ),
        migrations.DeleteModel(
            name="GiftOrder",
        ),
        migrations.DeleteModel(
            name="GiftPayment",
        ),
        migrations.DeleteModel(
            name="RefundOperation",
        ),
        migrations.DeleteModel(
            name="GiftProduct",
        ),
    ]
