# Generated by Django 5.1.4 on 2026-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_remove_giftactivationattempt_gift_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="last_penalty_payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Дата последней оплаты штрафа", null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_auto_generated",
            field=models.BooleanField(
                default=False,
                help_text="Автоматически созданный отзыв при отклонении заказа продавцом",
            ),
        ),
    ]
