# Generated by Django 5.1.4 on 2026-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_add_penalty_payment_date_and_auto_review_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_delivery_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Customer's requested delivery time. NULL = ASAP delivery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producer",
            name="max_orders_per_slot",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of scheduled orders per time slot (0 = unlimited)",
            ),
        ),
    ]
