# Generated by Django 5.1.4 on 2026-01-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_add_scheduled_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="producer",
            name="manual_closed_date",
            field=models.DateField(
                blank=True,
                help_text="Дата ручного закрытия магазина (для автосброса)",
                null=True,
            ),
        ),
    ]
